### ISSUE TITLE
Nimhawk requires port `localhost:80` regardless of configuration

### ISSUE THREAD

**Issue by anoduck** [hdbreaker/Nimhawk#11]
## User Error: Just ignore this.

------------------------------------

In the least, this information should be included in the `README.md` file to save everyone the trouble and the time:

### Port 80 appears to be a hardcoded requirement

Nimhawk appears to check to see if port 80 is open and available first thing after execution. If port 80 is being used by another program, Nimhawk outputs an error and shutsdown. This portcheck occurs before any of the configuration files are read, and it appears to be hardcoded somewhere in the framework. Port 80 has been replaced with port 8080 in the configuration file, the environment variables, in the dockerfile, and in the application itself at `server/admin_web_ui/pages/server.tsx`. The result of the modifications is nil, Nimhawk still checks for port 80, and stills shutdown when port 80 is busy. This is frustrating.

```bash
Get "http://localhost/v2/": dial tcp [::1]:80: connect: connection refused
```

I am currently running docker in headless mode, and do not know if this is effecting Nimhawk or not. Testing is rather pointless if the port number cannot be modified.

**Comment by anoduck** [comment]
Sometimes, I swear, I go full retard... I don't know what I was thinking.

-------------------------------------------

### Server configuration

It's not that difficult, Anoduck.

```toml
# IMPLANT CONFIGURATION                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                  
[admin_api]                                                                                                                                                                                                                                                                       
# Configure the API for the C2 server here. Recommended to keep at 127.0.0.1, change IP to 0.0.0.0 to listen on all interfaces.                                                                                                                                                   
ip = "0.0.0.0"                                                                                                                                                                                                                                                                    
# Configure port for the web interface of the C2 server, including API                                                                                                                                                                                                            
port = 9669                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                  
[implants_server]                                                                                                                                                                                                                                                                 
# Configure listener type (HTTP or HTTPS)                                                                                                                                                                                                                                         
type = "HTTP"                                                                                                                                                                                                                                                                     
# Certificate and key path used for 'HTTPS" listener type                                                                                                                                                                                                                         
sslCertPath = ""                                                                                                                                                                                                                                                                  
sslKeyPath = ""                                                                                                                                                                                                                                                                   
# Configure the hostname for Implant to connect to                                                                                                                                                                                                                                
# Leave as "" for IP:PORT-based connections                                                                                                                                                                                                                                       
hostname = "fullretard.com"                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                  
# Configure listener port where implant "team server" will wait for connections, mandatory even if hostname is specified                                                                                                                                                          
port = 8080                                                                                                                                                                                                                                                                       
# Configure the URI paths used for C2 communications                                                                                                                                                                                                                              
registerPath = "/register"                                                                                                                                                                                                                                                        
taskPath = "/task"                                                                                                                                                                                                                                                                
resultPath = "/result"                                                                                                                                                                                                                                                            
reconnectPath = "/reconnect"                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                  
[implant]                                                                                                                                                                                                                                                                         
# Public implants_server IP:                                                                                                                                                                                                                                                      
implantCallbackIp = "8.8.8.8"                                                                                                                                                                                                                                              
# Allow risky commands such as 'execute-assembly', 'powershell', or 'shinject' - operator discretion advised                                                                                                                                                                      
riskyMode = true                                                                                                                                                                                                                                                                  
# Enable Ekko sleep mask instead of a regular sleep() call                                                                                                                                                                                                                        
# Only available for (self-deleting) executables, not for DLL or shellcode                                                                                                                                                                                                        
sleepMask = false                                                                                                                                                                                                                                                                 
# Configure the default sleep time in seconds                                                                                                                                                                                                                                     
sleepTime = 10                                                                                                                                                                                                                                                                    
# Configure the default sleep jitter in %                                                                                                                                                                                                                                         
sleepJitter = 0                                                                                                                                                                                                                                                                   
# Configure the kill date for Implants (format: yyyy-MM-dd)                                                                                                                                                                                                                       
# Implants will exit if this date has passed                                                                                                                                                                                                                                      
killDate = ""                                                                                                                                                                                                                                                                     
# Configure the user-agent that Implants use to connect                                                                                                                                                                                                                           
# Also used by the server to verify Implant traffic                                                                                                                                                                                                                               
# Choosing an inconspicuous but uncommon user-agent is therefore recommended                                                                                                                                                                                                      
userAgent = "Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko"                                                                                                                                                                                                      
httpAllowCommunicationKey = "Some really really long string, but not retardly long"                                                                                                                                                                                                   
# Maximum number of reconnection attempts before retrying full registration                                                                                                                                                                                                       
maxReconnectionAttemps = 3                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                  
[auth]                                                                                                                                                                                                                                                                            
# Authentication settings                                                                                                                                                                                                                                                         
enabled = true                                                                                                                                                                                                                                                                    
# Session duration in hours (default: 24)                                                                                                                                                                                                                                         
session_duration = 24                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                  
# User definitions                                                                                                                                                                                                                                                                
# Default user: admin@nimhawk.com / P4ssw0rd123$                                                                                                                                                                                                                                  
[[auth.users]]                                                                                                                                                                                                                                                                    
email = "don't_go_full_retard@nimhawk.com"                                                                                                                                                                                                                                                     
password = "Nobody goes full retard, except Sean Penn in IamSam"                                                                                                                                                                                                                    
admin = true                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                  
# You can add more users as needed                                                                                                                                                                                                                                                
# [[auth.users]]                                                                                                                                                                                                                                                                  
# email = "operator@nimhawk.com"                                                                                                                                                                                                                                                  
# password = "SecurePassword123!"
# admin = false
```

### Admin UI `.env` file

That was the server, which listens for clients on all IP addresses. It will prioritize connections on it's external IP address. So, this means you need to set the client to contact it on it's external IP address.

```.env
SERVER_IP=http://10.1.0.1
SERVER_PORT=9669                                                                                                                                                                                                                                                                  
IMPLANT_SERVER_IP=http://8.8.8.8                                                                                                                                                                                                                                           
IMPLANT_SERVER_PORT=8080
```

TADA! It works, like it always worked when given the correct configuration. 

Don't go full retard.
