### ISSUE TITLE
Backend error: `/api/auth/login 404`

### ISSUE THREAD

**Issue by anoduck** [hdbreaker/Nimhawk#8]
System: Kali Linux Rolling Release
Nim Ver: Current (built fresh a few days ago)
python: 3.12
Important Notation: Port 80 is currently in use by a web server.

Approach: Preferred install method was manual to avoid bloat of docker container service.

## Manual Install

Except for some unresolvable packages for implants, installation was without a hitch. Changed the implant server to listen on port 8800, rather than on 80 due to conflict with web server. Both backend and frontend launched, and Next.js did it's thing. NimHawk UI appeared, entered in configured username and password, and then received an error that the backend could not be contacted. Which was rather odd, because it was still at its default setting and was running on localhost.

## Rootless Docker install

Building the image was tricky, as the build seemed to hang every time when running the command `chmod -R 755 ./nimhawk/`. This command was commented from the Dockerfile, then the image could be built successfully. Once a successful build was accomplished, the command was run manually from the container shell, and encountered the same result. What should have taken less than a minute to complete, took over 10 minutes until finally canceled with no error output. The same command was run in the repository directory prior to building the image, so there should have been no issue running it. 

Unfortunately, the result of the docker build was to receive the same error as in the manual installation.

## Attempted resolution 1

After reviewing the dockerfile, I believed this was due to not exposing the backend and implant server. This has normally not been a requirement, but since the dockerfile includes it, it was worth giving it a try.

The result was this made no difference.

## Attempted resolution 2

Ran container exactly as advised `docker run -it -p 3000:3000 -p 9669:9669 -p 80:80 -p 443:443 -v nimhawk-data:/nimhawk/server nimhawk full` without detaching it from console. 

Result was the same. No Change.

![Image](https://github.com/user-attachments/assets/cd3fab11-cb39-4e30-bce0-96a2e4c46868)

**Comment by anoduck** [comment]
Changing the address variables from `localhost` to `0.0.0.0` got me to a 404 error. So, something is going on. The docker logs do indicate the `404` error is valid. `/api/auth/login 404`.

```bash
nimhawk  | 
nimhawk  |  ✓ Ready in 5.2s
nimhawk  |  ○ Compiling /_error ...
nimhawk  |  ✓ Compiled /_error in 27s (1177 modules)
nimhawk  |  GET /_next/static/webpack/8d57bdfcc1916b86.webpack.hot-update.json 404 in 30231ms
nimhawk  |  ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
nimhawk  |  ○ Compiling /login ...
nimhawk  |  ✓ Compiled /login in 15.8s (1549 modules)
nimhawk  |  GET /_next/static/webpack/8d57bdfcc1916b86.webpack.hot-update.json 404 in 14647ms
nimhawk  |  ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
nimhawk  |  GET /login 200 in 16174ms
nimhawk  |  GET /login 200 in 129ms
nimhawk  |  POST /0.0.0.0:9669/api/auth/login 404 in 94ms
nimhawk  |  POST /0.0.0.0:9669/api/auth/login 404 in 42ms
nimhawk  |  GET /admin 404 in 45ms
```

Log output from `server/logs/admin_api_nimhawk.log`:

```bash
[07:32:38]  DEBUG: Starting HTTP server on 0.0.0.0:8800
[07:32:38]  DEBUG:   api_create_workspace => /api/workspaces [POST, OPTIONS]
[07:32:38]  DEBUG:   api_delete_workspace => /api/workspaces/<workspace_uuid> [OPTIONS, DELETE]
[07:32:38]  DEBUG:   get_nimplants_in_workspace => /api/workspaces/<workspace_uuid>/nimplants [GET, HEAD, OPTIONS]
[07:32:38]  DEBUG:   assign_to_workspace => /api/workspaces/assign [POST, OPTIONS]
[07:32:38]  DEBUG:   remove_from_workspace => /api/workspaces/remove [POST, OPTIONS]
[07:34:02]  DEBUG: [ERROR HANDLER] Unhandled exception: NotFound - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[07:34:02]  DEBUG: [ERROR HANDLER] Unhandled exception: InternalServerError - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```


Adding the config file to the `docker-compose.yaml` file will prevent configuration settings from returning to their default values every restart.

![Image](https://github.com/user-attachments/assets/be6f9acb-a86b-4aec-a650-c0f24e926810)

----

## Nimhawk setup files

Below is the copy of my configuration for Nim Hawk, and below that is the docker-compose file I am using to launch the
servers. Nothing should be out of place, and modifications are minor.

### Config.toml file

```toml
# IMPLANT CONFIGURATION

[admin_api]
# Configure the API for the C2 server here. Recommended to keep at 127.0.0.1, change IP to 0.0.0.0 to listen on all interfaces.
ip = "0.0.0.0"
#ip = "127.0.0.1"
# Configure port for the web interface of the C2 server, including API
port = 9669

[implants_server]
# Configure listener type (HTTP or HTTPS)
type = "HTTP"
# Certificate and key path used for 'HTTPS" listener type
sslCertPath = ""
sslKeyPath = ""
# Configure the hostname for Implant to connect to
# Leave as "" for IP:PORT-based connections
hostname = ""

# Configure listener port where implant "team server" will wait for connections, mandatory even if hostname is specified
port = 8800  #<-- Since port 80 is currently occupied.
# Configure the URI paths used for C2 communications
registerPath = "/register"
taskPath = "/task"
resultPath = "/result"
reconnectPath = "/reconnect" 

[implant]
# Public implants_server IP:
implantCallbackIp = "192.168.100.1"
# Allow risky commands such as 'execute-assembly', 'powershell', or 'shinject' - operator discretion advised
riskyMode = true
# Enable Ekko sleep mask instead of a regular sleep() call
# Only available for (self-deleting) executables, not for DLL or shellcode
sleepMask = false
# Configure the default sleep time in seconds
sleepTime = 10
# Configure the default sleep jitter in %
sleepJitter = 0
# Configure the kill date for Implants (format: yyyy-MM-dd)
# Implants will exit if this date has passed
killDate = ""
# Configure the user-agent that Implants use to connect
# Also used by the server to verify Implant traffic
# Choosing an inconspicuous but uncommon user-agent is therefore recommended
userAgent = "Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko"
httpAllowCommunicationKey = "XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXx"
# Maximum number of reconnection attempts before retrying full registration
maxReconnectionAttemps = 3

[auth]
# Authentication settings
enabled = true
# Session duration in hours (default: 24)
session_duration = 24

# User definitions
# Default user: admin@nimhawk.com / P4ssw0rd123$
[[auth.users]]
email = "user@nimhawk.com"
password = "XxXxXxXxXxXxXxXxXxXxXxXx"
admin = true

# You can add more users as needed
# [[auth.users]]
# email = "operator@nimhawk.com"
# password = "SecurePassword123!"
# admin = false
```

### Docker Compose file

```yaml
services:
  app:
    build: .
    image: localhost/nimhawk:latest
    container_name: nimhawkbox
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "3000:3000"
      - "8800:8800"
      - "9669:9669"
    expose:
      - "3000"
      - "8800"
      - "9669"
    entrypoint: /usr/local/bin/entrypoint.sh full
    volumes:
      - ./server/nimhawk.db:/nimhawk/server/nimhawk.db
      - ./config.toml:/nimhawk/config.toml
      - ./server/admin_web_ui/.env:/nimhawk/server/admin_web_ui/.env
```

### Dot Env

```.env
SERVER_IP=0.0.0.0
SERVER_PORT=9669
IMPLANT_SERVER_IP=0.0.0.0
IMPLANT_SERVER_PORT=8800
```

----

Unless network addresses are set to `0.0.0.0`, the unable to connect to the backend error is received. Beginning to suspect, rootful docker configuration is a requirement.
